### ISSUE TITLE
Hit testing stopped from today (13th Oct 2020)

### ISSUE THREAD

**Issue by dirrogate** [stspanho/aframe-hit-test#1]
Hit test was working fine till today.
Now on same chrome version (latest) it just stopped from today.
AR view shows but no reticle shows.

**Comment by dirrogate** [comment]
edit: It now just changes to a screen that says "insert phone into cardboard holder" when clicking the AR button. (not the VR button)

**Comment by stspanho** [comment]
Can you try to use this version for aframe? 	

`<script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@6e3b6c84391d50b45a1a3e801b74ca9d03ac8c09/dist/aframe-master.min.js"></script>`

**Comment by dirrogate** [comment]
Just tried it - still no luck. Same error. It shows a screen with an icon of a phone in portrait to landscape mode with the "insert phone in Google Cardboard" message.  - This is when pressing the AR button (not the VR button)

**Comment by stspanho** [comment]
Can you post a link to the example?

**Comment by dirrogate** [comment]
Sure. Here's the link https://realvision.ae/clydexr/aframehittest/index.html

here's a video of what happens https://www.youtube.com/watch?v=RsS0R2rUCnQ
(samsung s8, latest google chrome) It used to work perfect till yesterday.
The link above has the version of aframe you recommended

**Comment by stspanho** [comment]
It looks like you're using a different version as me:

You're using this one:
`https://cdn.jsdelivr.net/gh/aframevr/aframe@6d16cae8bf1a52275c08ca5db739a5fd5b0e284f/dist/aframe-master.min.js`

Can you try this one:
`https://cdn.jsdelivr.net/gh/aframevr/aframe@6e3b6c84391d50b45a1a3e801b74ca9d03ac8c09/dist/aframe-master.min.js`

**Comment by dirrogate** [comment]
wow, yes. It works now. Strange, I was sure I copied the link exactly as you typed earlier.
However, one caveat:
- in latest chrome browser on Samsung S8 it works
- in latest Samsung Internet browser it also works, but the reticle is seen but is not finding planes, and only places the dino, on the reticle near the bottom of screen (almost default camera center)

Another question, would you advise to copy the CND version of Aframe you listed above to my own server - just so it does not break in the future? or is it better practice to keep it pointed at the main gits?

Best Regards

**Comment by stspanho** [comment]
I think the hit testing feature is only supported in Chrome for now. 

I would advise to keep this version for now but switch to a release version in the future. Since I was using some experimental features, I wasn't able to do this at the time. I would need to check again if it works with a release version.
