### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by Khodour** [stspanho/aframe-hit-test#3]
I've downloaded the files and test it its seems need to be updated

**Comment by RBOSAMIYA9** [comment]
Hey I have checked it  try following  glitch link 

To try actual project
- [https://xr-spinosaurus.glitch.me](https://xr-spinosaurus.glitch.me)

To view code in glitch or to remix glitch
-  [https://glitch.com/edit/#!/xr-spinosaurus](https://glitch.com/edit/#!/xr-spinosaurus)

**Comment by stspanho** [comment]
Hi,

It has been added by default in A-Frame, more info here https://medium.com/samsung-internet-dev/use-new-augmented-reality-features-with-just-a-few-lines-of-code-with-webxr-and-aframe-c6f3f5789345
